import { IntentDef } from "./matcher";

export const INTENTS: IntentDef[] = [
  {
    name: "assistant.stop",
    domain: "assistant",
    patterns: ["stop", "shut up", "be quiet", "cancel", "nevermind", "never mind", "stop talking"],
    keywords: ["stop talking"],
  },
  {
    name: "assistant.undo",
    domain: "assistant",
    patterns: ["undo", "undo that", "put it back", "revert", "revert that"],
  },
  {
    name: "assistant.repeat",
    domain: "assistant",
    patterns: ["repeat that", "say that again", "what did you say", "say it again", "repeat"],
  },
  {
    name: "assistant.again",
    domain: "assistant",
    patterns: ["do that again", "do it again", "once more"],
  },
  {
    name: "assistant.why",
    domain: "assistant",
    patterns: [
      "why",
      "why did that happen",
      "why did (the) lights *",
      "what just happened",
      "explain that",
    ],
    keywords: ["why did"],
  },
  {
    name: "routine.teach",
    domain: "routine",
    patterns: ["when i say *"],
    keywords: ["when i say"],
  },
  {
    name: "routine.run",
    domain: "routine",
    patterns: [
      "good night",
      "goodnight",
      "bedtime",
      "movie mode",
      "movie time",
      "i am leaving",
      "away mode",
      "morning mode",
      "i am home",
      "i am back",
    ],
    keywords: ["good night", "movie mode", "away", "good morning"],
  },
  {
    name: "lights.status",
    domain: "lights",
    patterns: [
      "which lights are on",
      "which lights are off",
      "what lights are on",
      "are (the) lights on",
      "are (the) lights off",
      "is (the) {desk|bed|sofa|shelf|ceiling} (light|lamp) on",
      "list (the) lights",
      "light status",
      "how bright are (the) lights",
      "what scene is (this|it|active)",
      "what scene",
      "which scene",
    ],
    keywords: ["which lights", "light status"],
  },
  {
    name: "lights.power",
    domain: "lights",
    patterns: [
      "{turn|switch|set|put} (the) {lights|light|everything} {on|off}",
      "{turn|switch} (my|the) {lights|light} {on|off}",
      "{turn|switch|set} * {on|off}",
      "{lights|light} {on|off}",
      "kill (the) lights",
      "shut (the) lights off",
      "shut off (the) lights",
      "make it dark (in here)",
      "make it dark",
      "switch everything off",
      "turn everything off",
      "turn everything on",
      "lights out",
      "power {on|off}",
      "i cannot see",
      "it is too dark",
    ],
    keywords: ["lights", "light", "leds"],
  },
  {
    name: "lights.brightness",
    domain: "lights",
    patterns: [
      "{set|dim|put} (the) {lights|light} (to) *",
      "brightness *",
      "{lights|light} to *",
      "set brightness *",
      "dim (the) {lights|light}",
      "full brightness",
      "max (the) {lights|light|brightness}",
      "maximum brightness",
      "{lights|light} halfway",
      "half brightness",
    ],
    keywords: ["brightness", "percent"],
  },
  {
    name: "lights.relative",
    domain: "lights",
    patterns: [
      "(make it) {brighter|dimmer|darker}",
      "{brighter|dimmer|darker}",
      "a little {brighter|dimmer|darker}",
      "make (them|it) {brighter|dimmer|darker}",
      "make (them|it) (a bit|a little) {brighter|dimmer|darker}",
      "turn (it|them) {up|down}",
      "* turn (them|it) {up|down}",
      "turn (the) {lights|light} {up|down}",
      "{lights|light} {up|down}",
      "increase (the) brightness",
      "decrease (the) brightness",
    ],
    keywords: ["brighter", "dimmer", "darker"],
  },
  {
    name: "lights.color",
    domain: "lights",
    patterns: [
      "{turn|make|set} (the) {lights|light|them} *",
      "{lights|light} {red|blue|green|yellow|orange|purple|pink|white|cyan}",
    ],
    keywords: ["red", "blue", "green", "color", "colour"],
  },
  {
    name: "lights.temp",
    domain: "lights",
    patterns: [
      "(make it) {warmer|cooler}",
      "a little {warmer|cooler}",
      "make (them|it|the room) {warmer|cooler}",
      "make (the) room {warmer|cooler}",
      "{warmer|cooler}",
    ],
    keywords: ["warmer", "cooler", "color temperature"],
  },
  {
    name: "lights.scene",
    domain: "lights",
    patterns: [
      "{set|activate|enable} (the) {cozy|movie|night|bright|gaming} (scene|mode)",
      "{cozy|movie|night|bright|gaming} (scene|mode)",
    ],
    keywords: ["scene"],
  },
  {
    name: "media.mute",
    domain: "media",
    patterns: [
      "mute",
      "unmute",
      "mute (the) {music|volume|speakers}",
      "unmute (the) {music|volume|speakers}",
      "silence",
    ],
    keywords: ["mute", "unmute"],
  },
  {
    name: "media.play",
    domain: "media",
    patterns: [
      "{play|resume} (the) {music|song|track}",
      "play some music",
      "play music",
      "start (the) music",
      "pause (the) {music|song}",
      "stop (the) {music|song}",
      "pause",
      "play",
      "resume",
      "unpause",
    ],
    keywords: ["music", "pause"],
  },
  {
    name: "media.skip",
    domain: "media",
    patterns: [
      "{next|skip} (the) {song|track}",
      "previous (song|track)",
      "last song",
      "skip",
      "skip this",
      "next song",
      "next track",
    ],
    keywords: ["next song", "skip"],
  },
  {
    name: "media.volume",
    domain: "media",
    patterns: [
      "{set|turn} (the) volume (to) *",
      "volume *",
      "{louder|quieter}",
      "turn (it) {up|down}",
      "increase (the) volume",
      "decrease (the) volume",
      "volume up",
      "volume down",
    ],
    keywords: ["volume", "louder", "quieter"],
  },
  {
    name: "media.now",
    domain: "media",
    patterns: [
      "what is playing",
      "what is this song",
      "now playing",
      "what is the volume",
      "how loud is it",
    ],
    keywords: ["playing", "now playing"],
  },
  {
    name: "purifier.control",
    domain: "purifier",
    patterns: [
      "{turn|switch} (the) {purifier|air purifier|fan} {on|off}",
      "{purifier|fan} {on|off}",
      "set (the) {purifier|fan} to {auto|sleep|manual}",
      "fan speed *",
      "purifier sleep",
      "sleep mode (on the) purifier",
    ],
    keywords: ["purifier", "fan"],
  },
  {
    name: "air.query",
    domain: "purifier",
    patterns: [
      "how is (the) air",
      "air quality",
      "what is (the) aqi",
      "aqi",
      "filter",
      "filter health",
      "how is (the) filter",
    ],
    keywords: ["air quality", "aqi", "filter"],
  },
  {
    name: "weather.query",
    domain: "weather",
    patterns: [
      "what is (the) weather",
      "what is (the) {temperature|temp} (outside)",
      "how is (the) weather",
      "weather",
      "forecast",
      "what about tomorrow",
      "and tomorrow",
      "will it rain",
      "is it raining",
      "is it going to rain",
      "rain later",
      "weekend (weather|forecast)",
      "this weekend",
      "later today",
    ],
    keywords: ["weather", "forecast", "outside", "rain"],
  },
  {
    name: "climate.query",
    domain: "climate",
    patterns: [
      "what is (the) temperature (inside|in here)",
      "how hot is it",
      "how cold is it",
      "indoor temperature",
      "humidity",
      "how is (the) room",
      "is it cold (in here)",
      "is it hot (in here)",
      "is it comfortable",
    ],
    keywords: ["indoor", "humidity"],
  },
  {
    name: "calendar.query",
    domain: "calendar",
    patterns: [
      "what is next",
      "what is on (my) calendar",
      "what do i have today",
      "upcoming events",
      "what is coming up",
      "what is on today",
      "do i have anything (today)",
      "next event",
    ],
    keywords: ["calendar", "schedule", "events"],
  },
  {
    name: "timer.set",
    domain: "timer",
    patterns: [
      "{set|start} (a) timer *",
      "timer *",
      "remind me *",
      "set (my|an) alarm *",
      "set an alarm *",
      "wake me *",
      "alarm for *",
    ],
    keywords: ["timer", "remind", "alarm"],
  },
  {
    name: "timer.list",
    domain: "timer",
    patterns: [
      "what timers",
      "list (the) timers",
      "how long (is) left",
      "how long on (the) timer",
      "timer status",
      "what alarms",
      "when is (the) alarm",
    ],
    keywords: ["how long left"],
  },
  {
    name: "timer.cancel",
    domain: "timer",
    patterns: [
      "cancel (the) timer",
      "cancel (the) alarm",
      "stop (the) timer",
      "cancel all timers",
      "cancel (the) timers",
      "clear timers",
    ],
  },
  {
    name: "system.dnd",
    domain: "system",
    patterns: [
      "do not disturb",
      "do not disturb {on|off}",
      "quiet hours",
      "dnd",
      "dnd {on|off}",
      "turn (on) do not disturb",
      "turn off do not disturb",
      "enable do not disturb",
      "disable do not disturb",
    ],
    keywords: ["do not disturb", "quiet hours", "dnd"],
  },
  {
    name: "system.status",
    domain: "system",
    patterns: [
      "is everything working",
      "status",
      "system status",
      "are you there",
      "health",
      "ping",
    ],
    keywords: ["working", "offline"],
  },
  {
    name: "system.time",
    domain: "system",
    patterns: [
      "what time is it",
      "what is the time",
      "what is the date",
      "what day is it",
      "how late is it",
      "what day we on",
      "what is today date",
      "today date",
      "todays date",
      "tell me the date",
      "tell me the time",
    ],
  },
  {
    name: "system.help",
    domain: "system",
    patterns: ["help", "what can you do", "commands", "list commands"],
  },
  {
    name: "social.hello",
    domain: "social",
    patterns: [
      "hello",
      "hi",
      "hey",
      "hey nova",
      "hi nova",
      "hello nova",
      "yo",
      "nova",
      "good evening",
      "good afternoon",
    ],
  },
  {
    name: "social.how",
    domain: "social",
    patterns: ["how are you", "how are you doing", "you good"],
  },
  {
    name: "social.bye",
    domain: "social",
    patterns: ["bye", "goodbye", "see you", "good night nova", "later"],
  },
  {
    name: "social.thanks",
    domain: "social",
    patterns: ["thanks", "thank you", "cheers"],
  },
  {
    name: "social.who",
    domain: "social",
    patterns: ["who are you", "what is your name", "what are you"],
  },
  {
    name: "easter.podbay",
    domain: "social",
    patterns: ["open the pod bay doors", "open the pod bay doors please"],
  },
];
