import { filledSizes, nodesFor, SlopDef, SlopNode } from "./schema";

export const WIDGET_FORMAT = "judie-widget";
export const LEGACY_WIDGET_FORMAT = "nova-widget";
export const WIDGET_FORMAT_VERSION = 1;

export interface WidgetExportFile {
  format: typeof WIDGET_FORMAT | typeof LEGACY_WIDGET_FORMAT;
  version: number;
  widget: SlopDef;
}

export function serializeWidget(def: SlopDef): string {
  const file: WidgetExportFile = {
    format: WIDGET_FORMAT,
    version: WIDGET_FORMAT_VERSION,
    widget: { ...def, sizes: filledSizes(def) },
  };
  return JSON.stringify(file, null, 2);
}

export function parseWidgetFile(text: string): SlopDef {
  const data = JSON.parse(text) as Partial<WidgetExportFile> & { widget?: SlopDef };
  const widget = data.widget ?? (data as unknown as SlopDef);
  if (!widget || typeof widget !== "object" || !widget.id || !widget.layouts) {
    throw new Error("Not a Judie widget export");
  }
  if (data.format && data.format !== WIDGET_FORMAT && data.format !== LEGACY_WIDGET_FORMAT) {
    throw new Error("Not a Judie widget export");
  }
  return widget as SlopDef;
}

export function slugName(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "widget";
}

function hookComment(node: SlopNode) {
  const id = node.descriptor?.trim();
  const note = node.hook?.trim();
  if (!id && !note) return `  // (no descriptor) ${node.kind} "${node.text ?? ""}"`.trimEnd();
  if (id && note) return `  // @hook ${id} — ${note}`;
  if (id) return `  // @hook ${id}`;
  return `  // @hook — ${note}`;
}

function nodeLine(node: SlopNode) {
  const hook = node.descriptor?.trim();
  const attrs = [
    hook ? `data-hook="${hook}"` : null,
    `data-kind="${node.kind}"`,
    `data-id="${node.id}"`,
    `style={{ left: "${node.x}%", top: "${node.y}%", width: "${node.w}%", height: "${node.h}%" }}`,
  ]
    .filter(Boolean)
    .join(" ");
  const inner = node.text ? node.text.replace(/\n/g, " ") : "";
  return `      <div ${attrs}>${inner}</div>`;
}

export function exportHookCode(def: SlopDef): string {
  const hooks = filledSizes(def).flatMap((size) =>
    nodesFor(def, size).map((node) => ({
      size,
      id: node.id,
      kind: node.kind,
      descriptor: node.descriptor ?? "",
      hook: node.hook ?? "",
      previewText: node.text ?? "",
    }))
  );

  const layoutBlocks = filledSizes(def)
    .map((size) => {
      const nodes = nodesFor(def, size);
      const body = nodes.length
        ? nodes.map((n) => `${hookComment(n)}\n${nodeLine(n)}`).join("\n")
        : "      // empty layout";
      return `  "${size}": (
    <div className="widget-shell">
      <div className="widget-face">
${body}
      </div>
    </div>
  )`;
    })
    .join(",\n");

  return `/**
 * ${def.name}
 * Generated by Widget Creator.
 *
 * Descriptors are NOT visible on the widget. They mark hook points
 * so each element can be wired to live data or actions.
 */

export const widgetMeta = ${JSON.stringify(
    {
      id: def.id,
      name: def.name,
      sizes: filledSizes(def),
      background: def.background ?? null,
    },
    null,
    2
  )} as const;

export const hooks = ${JSON.stringify(hooks, null, 2)} as const;

export const layouts = {
${layoutBlocks}
};
`;
}

export function downloadText(filename: string, text: string, mime: string) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
