Section "Device"
    Identifier "PiFB"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "ShadowFB" "true"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "PiFB"
    DefaultDepth 16
EndSection
