Section "Device"
    Identifier "PiKMS"
    Driver "modesetting"
    Option "AccelMethod" "none"
    Option "PageFlip" "off"
    Option "ShadowFB" "true"
EndSection

Section "Monitor"
    Identifier "HDMI-1"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "PiKMS"
    Monitor "HDMI-1"
    DefaultDepth 24
EndSection
