#!/bin/sh
# Wait for DRM or a framebuffer so Xorg is not racing firmware/KMS.
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do
  if [ -e /dev/dri/card0 ] || [ -e /dev/fb0 ]; then
    sleep 3
    exit 0
  fi
  sleep 1
done
exit 0
